CharacterName = "Jeffry"
Class = "Fighter"
Level = 2
IsSubClassActiveSubclass = false
Subclass = "Champion"
Race = "Human"
PlayerName = "Jeff"
Backround = "bodyguard"

IsHPStatic = true # Determine if the AC is auto-calculated based on average calculation
IsHPRandomized = false # If someone wants to roll their HP based on their rolls, If it's set to True, the program will do the calculation of the HP 

Str = 16 
Dex = 12
Con = 16
Int = 12
Wis = 12
Chr = 10

Feats = []

Expertise = [
    "Insight",
    "Athletics"
]

Proficiencies = [
    "Intimidation",
    "Perception"
]

# ArmorType = ["Light","Medium","Heavy"] 
ArmorType = "Heavy"
ArmorAC = 16
Shield = true

[Weapons]
LongSword = "1d8"
LightCrossbow = "1d6"

Items = []

Gold = 10 

languages = ["Common","Arabic"]