CharacterName = "Jeffry"
Class = "Fighter"
Level = 2
IsSubClassActiveSubclass = false
Subclass = "Champion"
Race = "Human"
PlayerName = "Jeff"
Backround = "bodyguard"

IsHPStatic = true # Determine if the AC is auto-calculated based on average calculation
IsHPRandomized = false # If someone wants to roll their HP based on their rolls, If it's set to True, the program will do the calculation of the HP 

#Add Your Race Modifers as well 
Str = 16 
Dex = 12
Con = 16
Int = 12
Wis = 12
Chr = 10

Feats = []

#If you have expertice you only need to Insert the Value here :-)
Expertise = [
    "Insight",
    "Athletics"
]
#Add Your Race\Class Modifers as well
Proficiencies = [
    "Intimidation",
    "Perception"
]

# ArmorType = ["Light","Medium","Heavy"] 
ArmorType = "Heavy"
ArmorAC = 16
Shield = true


[Weapons]
LongSword = "1d8"
LightCrossbow = "1d6"

[ConsumeAbles]
#Item = Amount
AlchemistsFire = 1  

RegularItems = ["shovel", "gotic hunter hat"]

Gold = 10 
#Add Backround and Race 
languages = ["Common","Arabic"]