CharacterName = "Jeffry"
Class = "Fighter"
Level = 2
Subclass = false
Race = "Human"
PlayerName = "Jeff"
Backround = "bodyguard"

IsHPStatic = true # Determine if the AC is auto-calculated based on average calculation
IsHPRandomized = false # If someone wants to roll their HP based on their rolls, If it's set to True, the program will do the calculation of the HP 

STR = 16
Dex = 12
CON = 16
INT = 12
WIS = 12
CHR = 10

DexACModifier = false # If the armor does not scale with AC, for Example: ChainMail
Feats = []

Expertise = [
    "Insight"
]

proficiencies = [
    "Intimidation",
    "Perception"
]

[Armor]
ChainMail = 16
Shield = 2

[Weapons]
LongSword = "1d8"
LightCrossbow = "1d6"

Items = []

Gold = 10 

languages = ["Commen","Arabic"]